Added Deletion of Meal Entries and Meal Options
AY2425S1-CS2113-W12-1/tp pull request #42
Opened 2024-10-06 20:24 UTC by DarkDragoon2002

Added Functions for deletion of meals and meal entries
Added Functions to print separator message and just text
Edited HistoryTracker to not print out every loaded entry
Updated EXPECTED.TXT

2024-10-07 03:45 UTC, kennethSty requested changes
Great changes! I just noted two minor points to modify. One in order to adhere to the DRY principle and one to make the function name ..WithoutMsg more descriptive. *What does Msg mean?

2024-10-07 03:45 UTC, kennethSty commented on src/main/java/seedu/healthmate/HistoryTracker.java
> +            mealEntriesList.addMealWithoutMsg(meal);
Great changes! But could you please use a more descriptive name than ..Msg?

2024-10-07 03:45 UTC, kennethSty commented on src/main/java/seedu/healthmate/MealEntriesList.java
> +    @Override
As MealEntriesList inherits from MealList I think we do not need this function here as it only overwrites the feedback print statements to the user from:
"Meal index needs to be an integer" to 
"Meal Entry index needs to be an integer"

 To avoid violating the DRY principle, I would not include this method.

2024-10-07 07:53 UTC, kennethSty commented on src/main/java/seedu/healthmate/MealEntriesList.java
> +    @Override
Ignore this comment for now.  I think you have a valid point in reducing some ambiguity for the user. :)

2024-10-08 02:38 UTC, DarkDragoon2002 commented on src/main/java/seedu/healthmate/HistoryTracker.java
> +            mealEntriesList.addMealWithoutMsg(meal);
Hi, changed name of method to addMealWithoutCLIMsg to make it clearer. It is to add the meals to the various lists without spamming the user with messages

2024-10-09 05:08 UTC, kennethSty approved these changes

2024-10-09 05:09 UTC, merged